import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import Page from '../layouts/Page'
import { fetchDb, getExcerpt, prefixSiteUrl } from "../helpers/helpers"
import circleDownChevron from '../public/img/circled-down-chevron.svg'
import githubIcon from '../public/img/github.svg'
import emailIcon from '../public/img/email.svg'
import phoneIcon from '../public/img/phone.svg'
import kevinImg from '../public/img/Kevin.png'

export default function Home({ menuItems, projects, homePageContent }) {
  const skills = homePageContent.data.attributes.Skills.data

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page menuItems={menuItems}>
        <section className="container mx-auto my-8 p-4 border-bottom border-brand-gray flex items-center gap-12">
          <div className='basis-1/2'>
            <h1 className='font-serif text-6xl mb-4'>
              <span className="font-bold">Hello!</span><br />
              <em>I'm </em>
              <span className="font-bold highlight">Kevin Kowalski</span>
            </h1>
            <p className='font-bold mb-4'>Developer, Marketer, & Technology Enthusiast</p>
            <p className='mb-4'>Hi! I'm a web devleoper with a love of making websites for people and businesses alike. I currently work for a law firm updating and maintaining their website on a daily basis. I love to transform ideas into fully featured websites that make heads turn.</p>
            <p className='mb-4'>Ready to start a project together?</p>
            <Link href="#contact" className='inline-flex gap-4 relative items-center mb-16'>
              <Image src={circleDownChevron} alt="" />
              LET'S TALK
              <div className='w-24 h-px bg-brand-gray'></div>
            </Link>
          </div>
          <div className='basis-1/2'>
            <Image src={kevinImg} alt="Kevin Kowalski" />
          </div>
        </section>
        <section id="work" className="container mx-auto my-8 p-4">
          <h2 className='font-serif text-5xl mb-4'>Previous Work</h2>
          {projects.data.map(project => {
            const { Title, Description, FeaturedImage } = project.attributes
            const { url, width, height, alternativeText } = FeaturedImage.data.attributes.formats.small
            return (
              <div key={project.id}>
                <Image src={prefixSiteUrl(url)} width={width} height={height} alt={alternativeText || Title} />
                <h3 className='font-serif text-4xl mb-4'>{Title}</h3>
                <p>{getExcerpt(Description)}</p>
              </div>
            )
          })}
        </section>
        <section id="skills" className='bg-brand-blue'>
          <div className='container mx-auto my-8 py-8 text-center'>
            <span className='text-white mb-4 block'>MY SKILLS</span>
            <h2 className='font-serif text-5xl mb-4 text-white'>What I Know</h2>
            <p className='text-white'>Forgive the tech jargon - these are ust some of the technologies and tools I'm familiar with.</p>
            <ul className='grid grid-cols-2 md:grid-cols-5 gap-y-16 mt-8'>
              {skills.map(skill => {
                const { id, attributes: { alternativeText, height, width, url } } = skill
                console.log(skill)
                return (
                  <li key={id} className="flex flex-col items-center">
                    <Image src={prefixSiteUrl(url)} className="h-24 w-24 object-contain" width={width} height={height} alt={alternativeText} />
                    <span className='text-white mt-4'>{alternativeText}</span>
                  </li>
                )
              })}
            </ul>
          </div>
        </section>
        <section id="contact" className='container mx-auto my-8'>
          <span className='mb-4 block text-center'>LET'S WORK TOGETHER</span>
          <h2 className='font-serif text-5xl mb-4 text-center'>Contact Me</h2>
          <p className='text-center'>I can't wait to discuss your needs for a new website. Let's chat and turn your ideas into a digital reality!</p>
          <div className='flex flex-wrap my-16 gap-20 justify-center items-center text-brand-gray'>
            <form className='flex flex-col gap-4'>
              <div class="relative">
                <input type="text" id="name" class="w-full py-2 px-4 border border-brand-gray peer" placeholder=" " />
                <label for="name" class="absolute duration-300 transform -translate-y-4 scale-75 top-2 bg-white px-2 peer-focus:px-2 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Name</label>
              </div>
              <div class="relative">
                <input type="email" id="email" class="w-full py-2 px-4 border border-brand-gray peer" placeholder=" " />
                <label for="email" class="absolute duration-300 transform -translate-y-4 scale-75 top-2 bg-white px-2 peer-focus:px-2 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Email</label>
              </div>
              <div class="relative">
                <textarea id="message" class="w-full py-2 px-4 border border-brand-gray peer" placeholder=" " />
                <label for="message" class="absolute duration-300 transform -translate-y-4 scale-75 top-2 bg-white px-2 peer-focus:px-2 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Message</label>
              </div>
              <button type="submit" className='bg-brand-blue py-2'>LET'S TALK</button>
            </form>
            <ul className='flex flex-col gap-6'>
              <li>
                <Link href="mailto:kevinrkowalski@gmail.com" className='flex items-center gap-4'>
                  <Image src={emailIcon} alt="" />
                  kevinrkowalski@gmail.com
                </Link>
              </li>
              <li>
                <Link href="tel:401-484-1232" className='flex items-center gap-4'>
                  <Image src={phoneIcon} alt="" />
                  (401) 484-1232
                </Link>
              </li>
              <li>
                <Link href="https://github.com/kevinrkowalski" className='flex items-center gap-4'>
                  <Image src={githubIcon} alt="" />
                  github.com/kevinrkowalski
                </Link>
              </li>
            </ul>
          </div>
        </section>
      </Page>
    </>
  )
}

export async function getServerSideProps() {
  const menuItems = await fetchDb('menus?filters\[slug\][$eq]=main-nav&populate=*')
  const projects = await fetchDb('projects?populate=FeaturedImage')
  const homePageContent = await fetchDb('home-page?populate=*')

  return {
    props: {
      menuItems,
      projects,
      homePageContent
    }
  }
}
